import { useEffect, useMemo, useRef, useState } from 'react'
import { ArrowRight, AudioLines, Check, Copy, Crown, Hand, Headphones, Loader2, LockKeyhole, MessageCircle, Mic, MicOff, PhoneOff, Plus, Radio, Search, Send, Sparkles, Users, X } from 'lucide-react'
import { ProfileAvatar } from '@/components/profile/ProfileAvatar'
import { cn } from '@/components/ui/utils'
import type { RoomDraft, SpeakingCommunity } from '@/hooks/useSpeakingCommunity'
import { useCommunityCopy } from '@/i18n/community'
import type { CommunityChampion } from '@/lib/profileApi'

const KINDS = { conversation: 'Conversation', debate: 'Debate', ielts: 'IELTS practice' }
const LEVELS = { all: 'All levels', beginner: 'Beginner', intermediate: 'Intermediate', advanced: 'Advanced' }
const DEFAULT_DRAFT: RoomDraft = { title: '', topic: '', kind: 'conversation', level: 'all', capacity: 5, private: false }

export default function SpeakingHub({ hub, champion, invitedRoom }: { hub: SpeakingCommunity; champion: CommunityChampion | null; invitedRoom: string | null }) {
  const t = useCommunityCopy()
  const [creating, setCreating] = useState(false)
  const [kind, setKind] = useState('all')
  const [query, setQuery] = useState('')
  const [level, setLevel] = useState('all')
  const [text, setText] = useState('')
  const [copied, setCopied] = useState(false)
  const [shareUrl, setShareUrl] = useState('')
  const chatRef = useRef<HTMLDivElement>(null)
  const lobbyRef = useRef<HTMLElement>(null)
  const visible = useMemo(() => hub.rooms.filter(room => (kind === 'all' || room.kind === kind) && (level === 'all' || room.level === 'all' || room.level === level) && `${room.title} ${room.topic}`.toLowerCase().includes(query.toLowerCase())), [hub.rooms, kind, level, query])
  useEffect(() => { chatRef.current?.scrollTo({ top: chatRef.current.scrollHeight, behavior: 'smooth' }) }, [hub.messages])
  useEffect(() => { if (hub.room) setCreating(false); setCopied(false); setShareUrl('') }, [hub.room?.id])
  const room = hub.room
  const share = async () => {
    if (!room) return
    const url = new URL('/community', window.location.origin)
    url.searchParams.set('room', room.id)
    setShareUrl(url.toString())
    try { await navigator.clipboard.writeText(url.toString()); setCopied(true) } catch { setCopied(false) }
  }
  return <section className="speaking-hub" aria-label={t('Speaking community')}>
    {hub.error ? <div className="hub-feedback is-error" role="alert"><span>{hub.error}</span><button type="button" onClick={hub.clearError} aria-label={t('Close')}><X size={17} /></button></div> : null}
    {hub.notice ? <div className="hub-feedback" role="status">{hub.notice}</div> : null}
    {hub.invitation ? <div className="hub-invitation" role="status"><span className="hub-invite-icon"><Headphones /></span><div><b>{t('Speaking invitation')}</b><p>@{hub.invitation.from.name} {t('invites you to a private voice conversation.')}</p></div><button type="button" className="hub-button is-primary" disabled={hub.busy || !!room} onClick={() => void hub.reply(true)}>{t('Accept & join')}</button><button type="button" className="hub-button" onClick={() => void hub.reply(false)}>{t('Decline')}</button></div> : null}
    {room ? <>
      <header className="hub-room-header"><div><span className="hub-eyebrow"><Radio size={14} />{t(room.private ? 'Private room' : 'Live')} · {t(KINDS[room.kind as keyof typeof KINDS])}</span><h2>{room.title}</h2><p>{room.members.length}/{room.capacity} · {t(LEVELS[room.level as keyof typeof LEVELS])}</p></div><button type="button" className="hub-button" onClick={() => void share()}>{copied ? <Check size={17} /> : <Copy size={17} />}{t(copied ? 'Link copied' : 'Invite friends')}</button></header>
      {shareUrl ? <label className="hub-share-link">{t('Invitation link')}<input readOnly value={shareUrl} onFocus={event => event.target.select()} /></label> : null}
      <div className="hub-session-layout"><div className="hub-session-main">
        <div className={cn('hub-topic', room.kind === 'debate' && 'is-debate')}><span className="hub-eyebrow"><Sparkles size={14} />{t(KINDS[room.kind as keyof typeof KINDS])}</span><h3>{room.topic}</h3><p>{t('Listen, take turns and challenge ideas respectfully. Raise your hand when you want to speak.')}</p>{room.kind === 'debate' ? <div className="hub-debate-sides" aria-label={t('Choose your side')}>{['for', 'against'].map(side => <button type="button" key={side} aria-pressed={hub.self?.side === side} onClick={() => hub.changeState({ side: hub.self?.side === side ? '' : side })}>{t(side === 'for' ? 'For' : 'Against')} · {room.members.filter(member => member.side === side).length}</button>)}</div> : null}</div>
        <div className="hub-speakers">{room.members.map(member => <article key={member.id} className={cn('hub-speaker', !member.muted && 'is-speaking', member.hand && 'has-hand')}><div className="hub-speaker-avatar"><ProfileAvatar src={member.avatarUrl} name={member.name} alt="" />{member.hand ? <span className="hub-raised-hand" aria-label={t('Raise hand')}><Hand size={14} /></span> : null}</div><b>@{member.name}</b><span>{member.id === hub.selfId ? t('You') : member.id === room.hostId ? t('Host') : member.side ? t(member.side === 'for' ? 'For' : 'Against') : t('Live')}</span><small>{member.muted ? <MicOff size={12} /> : <Mic size={12} />}{member.id !== hub.selfId && hub.peerStates[member.id] !== 'connected' ? t(hub.peerStates[member.id] === 'failed' || hub.peerStates[member.id] === 'disconnected' ? 'Audio interrupted' : 'Connecting audio') : t(member.muted ? 'Muted' : 'Mic on')}</small>{hub.selfId === room.hostId && member.id !== hub.selfId ? <button type="button" className="hub-remove" aria-label={`${t('Remove from room')}: ${member.name}`} title={t('Remove from room')} onClick={() => hub.remove(member.id)}><X size={14} /></button> : null}</article>)}{Array.from({ length: Math.max(0, room.capacity - room.members.length) }, (_, index) => <div className="hub-speaker is-empty" key={`empty-${index}`}><span className="hub-empty-seat"><Users size={23} /></span><small>{t('Open seat')}</small></div>)}</div>
        <div className="hub-call-controls"><button type="button" className={cn('hub-button', !hub.self?.muted && 'is-primary')} onClick={() => hub.changeState({ muted: !hub.self?.muted })}>{hub.self?.muted ? <MicOff size={18} /> : <Mic size={18} />}{t(hub.self?.muted ? 'Unmute' : 'Mute')}</button><button type="button" className={cn('hub-button', hub.self?.hand && 'is-selected')} aria-pressed={hub.self?.hand === true} onClick={() => hub.changeState({ hand: !hub.self?.hand })}><Hand size={18} />{t(hub.self?.hand ? 'Lower hand' : 'Raise hand')}</button><button type="button" className="hub-button is-leave" onClick={hub.leave}><PhoneOff size={18} />{t('Leave room')}</button></div>
      </div><aside className="hub-chat"><h3><MessageCircle size={18} />{t('Room chat')}</h3><div className="hub-chat-messages" ref={chatRef} role="log" aria-live="polite">{hub.messages.length ? hub.messages.map(message => <div key={message.id} className="hub-chat-message"><div><b>@{message.name}</b><time dateTime={message.createdAt}>{new Date(message.createdAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</time></div><p>{message.text}</p></div>) : <p className="hub-chat-empty">{t('Say hello or share a question.')}</p>}</div><form onSubmit={event => { event.preventDefault(); if (text.trim()) { hub.chat(text.trim()); setText('') } }}><input value={text} onChange={event => setText(event.target.value)} maxLength={500} placeholder={t('Write a message')} aria-label={t('Write a message')} /><button type="submit" disabled={!text.trim()} aria-label={t('Send')}><Send size={18} /></button></form></aside></div>
      {Object.entries(hub.streams).map(([id, stream]) => <RemoteAudio key={id} stream={stream} />)}
    </> : <>
      <div className="hub-hero"><div className="hub-hero-copy"><span className="hub-eyebrow"><AudioLines size={16} />{t('Speaking community')}<span className={cn('hub-connection', hub.connected && 'is-live')}>{t(hub.connected ? 'Live' : 'Connecting…')}</span></span><h1>{t('A little courage. A real conversation.')}</h1><p>{t('Meet someone new, practise your English and find your people. Your next conversation starts here.')}</p><div className="hub-hero-actions"><button type="button" className="hub-button is-primary" disabled={!hub.connected || hub.busy} onClick={() => setCreating(true)}><Plus size={19} />{t('Create a room')}</button><button type="button" className="hub-button" onClick={() => lobbyRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' })}>{t('Explore rooms')}<ArrowRight size={17} /></button></div><div className="hub-hero-stats"><span><i /> <b>{hub.connected ? hub.online : '—'}</b> {t('online in community')}</span><span><Users size={15} /><b>{hub.connected ? hub.rooms.length : '—'}</b> {t('rooms open')}</span></div></div><div className="hub-voice-art" aria-hidden="true"><div className="hub-orbit is-outer" /><div className="hub-orbit is-inner" /><span className="hub-art-core"><Mic size={42} /></span><span className="hub-art-bubble is-a"><MessageCircle size={24} /></span><span className="hub-art-bubble is-b"><Headphones size={25} /></span><span className="hub-art-bubble is-c"><Users size={24} /></span><div className="hub-art-caption"><span>{Array.from({ length: 13 }, (_, i) => <i key={i} style={{ '--bar-height': `${[10, 20, 14, 30, 22, 38, 26][i % 7]}px`, animationDelay: `${i * .12}s` } as React.CSSProperties} />)}</span><small>{t('Your voice belongs here')}</small></div></div></div>
      {champion ? <div className="hub-champion" title={t('Highest total earned XP among learners with a public profile and visible leaderboard. Ties use streak, then join date. Updates every 30 seconds.')}><span className="hub-champion-crown"><Crown size={21} /></span><div><b>{t('Top learner today')}</b><span>@{champion.nickname} · {champion.xp.toLocaleString()} XP</span></div><small>{t('Highest total earned XP among learners with a public profile and visible leaderboard. Ties use streak, then join date. Updates every 30 seconds.')}</small></div> : null}
      {invitedRoom ? <div className="hub-invitation"><LockKeyhole size={22} /><div><b>{t('Invitation link')}</b><p>{t('Someone invited you to a speaking room.')}</p></div><button type="button" className="hub-button is-primary" disabled={!hub.connected || hub.busy} onClick={() => void hub.join(invitedRoom)}>{t('Join invited room')}<ArrowRight size={17} /></button></div> : null}
      <section ref={lobbyRef} className="hub-lobby"><div className="hub-lobby-heading"><h2><Radio size={21} />{t('Live rooms')}<span>{visible.length}</span></h2><button type="button" className="hub-button" disabled={!hub.connected || hub.busy} onClick={() => setCreating(true)}><Plus size={17} />{t('Create a room')}</button></div><div className="hub-lobby-filters"><nav aria-label={t('Room type')}>{Object.entries({ all: 'All rooms', ...KINDS }).map(([value, label]) => <button type="button" key={value} aria-pressed={kind === value} className={cn(kind === value && 'is-active')} onClick={() => setKind(value)}>{t(label)}</button>)}</nav><label className="hub-room-search"><Search size={16} /><input value={query} onChange={event => setQuery(event.target.value)} placeholder={t('Search rooms or topics')} aria-label={t('Search rooms or topics')} /></label><select value={level} onChange={event => setLevel(event.target.value)} aria-label={t('English level')}>{Object.entries(LEVELS).map(([value, label]) => <option key={value} value={value}>{t(label)}</option>)}</select></div><div className="hub-room-grid">{visible.map(room => <article key={room.id} className={`hub-room-card is-${room.kind}`}><div className="hub-room-card-top"><span className="hub-room-kind">{room.kind === 'debate' ? <AudioLines size={16} /> : room.kind === 'ielts' ? <Sparkles size={16} /> : <MessageCircle size={16} />}{t(KINDS[room.kind as keyof typeof KINDS])}</span><span className="hub-room-live"><i />{t('Live')}</span></div><h3>{room.title}</h3><p>{room.topic}</p><small>{t(LEVELS[room.level as keyof typeof LEVELS])}</small><div className="hub-room-card-bottom"><div className="hub-room-members">{room.members.slice(0, 3).map(member => <span key={member.id}><ProfileAvatar src={member.avatarUrl} name={member.name} alt="" /></span>)}<b>{room.members.length}/{room.capacity}</b></div><button type="button" className="hub-button" disabled={room.members.length >= room.capacity || !hub.connected || hub.busy} onClick={() => void hub.join(room.id)}>{t(room.members.length >= room.capacity ? 'Room full' : 'Join conversation')}<ArrowRight size={15} /></button></div></article>)}</div>{!visible.length ? <div className="hub-lobby-empty"><span><Headphones size={28} /></span><h3>{t('Start the first conversation')}</h3><p>{t('No rooms match these filters. Create a room and invite others to join you.')}</p></div> : null}</section>
    </>}
    {hub.busy ? <div className="hub-pending" role="status"><Loader2 className="animate-spin" size={17} />{t('Connecting…')}</div> : null}
    {creating ? <CreateRoom onClose={() => { if (hub.busy) hub.leave(); setCreating(false) }} onCreate={hub.create} busy={hub.busy} error={hub.error} /> : null}
  </section>
}

function CreateRoom({ onClose, onCreate, busy, error }: { onClose: () => void; onCreate: (draft: RoomDraft) => Promise<void>; busy: boolean; error: string }) {
  const t = useCommunityCopy()
  const [draft, setDraft] = useState<RoomDraft>(DEFAULT_DRAFT)
  const dialog = useRef<HTMLDialogElement>(null)
  useEffect(() => { dialog.current?.showModal() }, [])
  return <dialog className="hub-create-dialog" ref={dialog} onCancel={onClose} aria-labelledby="create-speaking-title"><form onSubmit={event => { event.preventDefault(); void onCreate(draft) }}><div className="hub-dialog-heading"><span className="hub-dialog-icon"><Mic size={24} /></span><button type="button" onClick={onClose} aria-label={t('Close')}><X size={20} /></button></div><h2 id="create-speaking-title">{t('Create a room')}</h2><label>{t('Room name')}<input autoFocus required maxLength={70} value={draft.title} onChange={event => setDraft({ ...draft, title: event.target.value })} /></label><label>{t('What will you talk about?')}<textarea required rows={3} maxLength={200} value={draft.topic} onChange={event => setDraft({ ...draft, topic: event.target.value })} /></label><div className="hub-form-grid"><label>{t('Room type')}<select value={draft.kind} onChange={event => setDraft({ ...draft, kind: event.target.value })}>{Object.entries(KINDS).map(([value, label]) => <option key={value} value={value}>{t(label)}</option>)}</select></label><label>{t('English level')}<select value={draft.level} onChange={event => setDraft({ ...draft, level: event.target.value })}>{Object.entries(LEVELS).map(([value, label]) => <option key={value} value={value}>{t(label)}</option>)}</select></label><label>{t('Seats')}<select value={draft.capacity} onChange={event => setDraft({ ...draft, capacity: Number(event.target.value) })}>{[2, 3, 4, 5, 6, 7, 8].map(value => <option key={value}>{value}</option>)}</select></label><label>{t('Private room')}<select value={draft.private ? 'private' : 'public'} onChange={event => setDraft({ ...draft, private: event.target.value === 'private' })}><option value="public">{t('Open to everyone')}</option><option value="private">{t('Private · invite link only')}</option></select></label></div><p>{t('Your mic starts muted. Rooms close when everyone leaves.')}</p>{error ? <div className="hub-feedback is-error" role="alert">{error}</div> : null}<div className="hub-dialog-actions"><button type="button" className="hub-button" onClick={onClose}>{t('Cancel')}</button><button type="submit" className="hub-button is-primary" disabled={busy || !draft.title.trim() || !draft.topic.trim()}>{busy ? <Loader2 size={18} className="animate-spin" /> : <Plus size={18} />}{t('Create a room')}</button></div></form></dialog>
}

function RemoteAudio({ stream }: { stream: MediaStream }) {
  const t = useCommunityCopy()
  const audio = useRef<HTMLAudioElement>(null)
  const [blocked, setBlocked] = useState(false)
  useEffect(() => { const element = audio.current; if (!element) return; element.srcObject = stream; void element.play().catch(() => setBlocked(true)); return () => { element.srcObject = null } }, [stream])
  return <><audio ref={audio} autoPlay playsInline />{blocked ? <button type="button" className="hub-button" onClick={() => void audio.current?.play().then(() => setBlocked(false)).catch(() => {})}><Headphones size={18} />{t('Tap to play audio')}</button> : null}</>
}
