// Founder-reported launch snapshot: 7 October 2026. Keep forecasts separate.
export const team = [
  { name: 'Elyor Nishonboyev', role: 'Founder & presenter' },
  { name: 'Amirbek Mansurov', role: 'Marketing' },
  { name: 'Davlat Erkinov', role: 'Developer' },
  { name: 'Alimqulov Firdavs', role: 'Developer' },
];

export const slides = [
  {
    id: 'opening', label: 'ProfAI', theme: 'dark', layout: 'cover',
    title: 'Exam preparation.\nConnected classrooms.',
    lead: 'IELTS, SAT and class management in one platform.',
    shortSeconds: 15, fullSeconds: 20,
    short: 'Assalomu alaykum. Men Elyor Nishonboyev, ProfAI asoschisiman. Biz IELTS va SAT tayyorgarligini o‘quv markazidagi sinf boshqaruvi bilan birlashtiryapmiz. O‘quvchi mashq qiladi, o‘qituvchi esa uning ishini va natijalarini shu platformada kuzatadi.',
    full: 'Assalomu alaykum. Men Elyor Nishonboyev, ProfAI asoschisiman. Biz IELTS va SAT tayyorgarligini o‘quv markazidagi sinf boshqaruvi bilan birlashtiryapmiz. Tasavvur qiling: o‘qituvchi uyga vazifa beradi, o‘quvchi uni bajaradi va keyingi darsda o‘qituvchi kimga qanday yordam kerakligini natijalardan ko‘ra oladi. ProfAI shu jarayonni bitta platformada bog‘laydi.',
  },
  {
    id: 'problem', label: 'The problem', theme: 'light', layout: 'problem',
    title: 'A homework task should\nlead to a clear next step.',
    lead: 'When practice and class management live apart, teachers have to reconnect the pieces.',
    shortSeconds: 20, fullSeconds: 30,
    short: 'Muammo shundaki, topshiriq berishning o‘zi yetarli emas. O‘qituvchi kim bajardi, kim qayerda qiynaldi va keyingi mashq qanday bo‘lishi kerakligini ham bilishi kerak. Materiallar, javoblar va natijalar alohida joylarda bo‘lsa, shu jarayonni kuzatish qiyinlashadi.',
    full: 'Bizning asosiy e’tiborimiz o‘quvchining mashqi va o‘qituvchining keyingi qarori orasidagi bog‘lanishga qaratilgan. Topshiriq berishning o‘zi yetarli emas. Kim bajardi? Kim muddatdan kechikdi? Qaysi mavzuda yordam kerak? Materiallar, javoblar va natijalar alohida joylarda bo‘lsa, o‘qituvchi ularni qayta yig‘ishi kerak. ProfAI bu ishni qanday yengillashtirishini markazlardagi sinov orqali tekshiryapmiz.',
  },
  {
    id: 'product', label: 'The product', theme: 'dark', layout: 'product',
    title: 'One platform.\nTwo sides of learning.',
    lead: 'Learners prepare for IELTS and SAT. Teachers manage the work around that practice.',
    shortSeconds: 20, fullSeconds: 30,
    short: 'ProfAI’da uchta asosiy yo‘nalish bor. IELTS’da to‘rtta ko‘nikma bo‘yicha mashq va sinovlar. SAT’da matematika hamda Reading and Writing tayyorgarligi. Classes’da esa o‘qituvchi guruhlarni boshqaradi, vazifa beradi va o‘quvchilar natijalarini kuzatadi.',
    full: 'ProfAI’da uchta asosiy yo‘nalish bor. IELTS’da Listening, Reading, Writing va Speaking bo‘yicha tayyorgarlik mavjud. SAT’da matematika hamda Reading and Writing yo‘nalishlari bor. O‘quvchi mashq qiladi, test ishlaydi va javoblarini tahlil qiladi. Classes moduli shu tayyorgarlikni o‘quv markazining kundalik ishi bilan bog‘laydi: guruhlar, topshiriqlar, muddatlar va natijalar bir joyda turadi.',
  },
  {
    id: 'workflow', label: 'Class workflow', theme: 'light', layout: 'workflow',
    title: 'A teacher can follow\nthe whole class in one place.',
    lead: 'Assign work, see completion, review recorded results and send a clear next step.',
    shortSeconds: 25, fullSeconds: 40,
    short: 'Mana jarayon: o‘qituvchi guruhga yoki alohida o‘quvchiga vazifa beradi va muddat belgilaydi. O‘quvchi uni ProfAI’da bajaradi. O‘qituvchi bajarilish holati va qayd etilgan natijalarni ko‘radi, so‘ng o‘quvchiga izoh yoki keyingi vazifani yuboradi. Shu sababli markazlar bilan ishlash biz uchun asosiy yo‘nalish.',
    full: 'Mana bitta sinf misolida jarayon. O‘qituvchi guruhga IELTS yoki SAT topshirig‘ini beradi va muddat belgilaydi. Zarur bo‘lsa, bitta o‘quvchiga alohida vazifa ham beradi. O‘quvchi topshiriqni ProfAI’da bajaradi. Sinf oynasida kim boshlagani, kim tugatgani va kim kechikkanini ko‘rish mumkin. O‘quvchi profilida esa qayd etilgan natijalar va ko‘nikmalar kesimidagi ma’lumotlar turadi. O‘qituvchi shu ma’lumot asosida izoh yuboradi yoki keyingi mashqni tanlaydi. Biz markazlarga aynan shu bog‘langan jarayonni taklif qilyapmiz.',
  },
  {
    id: 'traction', label: 'Early traction', theme: 'dark', layout: 'traction',
    title: 'Launched 3 days ago.\n40 users so far.',
    lead: 'Early adoption, with learning-center partnerships now in discussion.',
    shortSeconds: 20, fullSeconds: 30,
    short: 'Bugun ishga tushganimizning uchinchi kuni. Hozir 40 foydalanuvchimiz bor. Beshta o‘quv markazi bilan hamkorlik bo‘yicha muzokara olib boryapmiz va ularga 14 kunlik sinov taklif qilganmiz. Keyingi muhim dalilimiz: markazlarning muntazam foydalanishi va pullik xizmatga o‘tishga tayyorligi bo‘ladi.',
    full: 'Bugun ishga tushganimizning uchinchi kuni va hozir 40 foydalanuvchimiz bor. Beshta o‘quv markazi loyihaga qiziqish bildirdi. Ular bilan hamkorlik bo‘yicha kelishyapmiz va ularga 14 kunlik sinov taklif qilganmiz. Bu hali pullik shartnoma degani emas. Sinovning vazifasi markazlar mahsulotdan muntazam foydalanadimi, o‘qituvchilar uni kundalik ishiga qo‘shadimi va keyinchalik to‘lashga tayyormi, shuni aniqlash. Biz keyingi o‘sishni shu dalillar bilan baholaymiz.',
  },
  {
    id: 'position', label: 'Our positioning', theme: 'light', layout: 'position',
    title: 'Practice and class visibility\nin the same workflow.',
    lead: 'Our focus is the connection between exam practice and the teacher’s next decision.',
    shortSeconds: 15, fullSeconds: 25,
    short: 'O‘quv markazi bugun alohida test resurslari, xabar almashish vositalari va jadvallardan foydalanishi mumkin. Bizning e’tiborimiz IELTS va SAT mashqlarini sinfdagi topshiriq hamda o‘quvchi natijalari bilan bog‘lashga qaratilgan. Markazning ProfAI’ni tanlash sababini sinovdagi haqiqiy foydalanish orqali isbotlaymiz.',
    full: 'O‘quv markazlarida turli alternativalar bor: test tayyorgarligi resurslari, topshiriq yuborish uchun xabar almashish vositalari va natijalarni qayd etish uchun jadvallar. Ularning har biri foydali ishni bajaradi. Bizning e’tiborimiz esa IELTS va SAT mashqlarini sinfdagi topshiriq, bajarilish holati va o‘quvchi natijalari bilan bir jarayonda bog‘lashga qaratilgan. Bu ustunlikni umumiy da’vo bilan emas, markazlardagi sinov va qayta foydalanish bilan ko‘rsatmoqchimiz.',
  },
  {
    id: 'business', label: 'Business model', theme: 'dark', layout: 'business',
    title: 'Free trials first.\nPaid use when value is proven.',
    lead: 'Learner plans and a learning-center channel, with center terms still being discussed.',
    shortSeconds: 15, fullSeconds: 25,
    short: 'Daromad yo‘limiz ikki tomondan quriladi: mustaqil o‘quvchilar uchun pullik foydalanish va o‘quv markazlari orqali foydalanish. Markazlarga 14 kunlik sinov taklif qildik. Ular foydasini ko‘rsa, pullik hamkorlik shartlarini kelishamiz. Hozircha pullik markazlar yoki tushum bo‘yicha tasdiqlangan raqamni taqdim etmayapmiz.',
    full: 'Daromad modelimiz ikki tomondan quriladi: mustaqil o‘quvchilar uchun pullik foydalanish va o‘quv markazlari orqali foydalanish. Platformada o‘quvchi, markaz o‘quvchisi va o‘qituvchi uchun tariflar hamda qo‘shimcha foydalanish paketlari mavjud. Markazlar bilan yakuniy tijorat shartlari hali muzokarada. Ularga 14 kunlik sinov taklif qilganmiz. Sinovdan keyin foydalanish, fikr-mulohaza va to‘lashga tayyorlik asosida hamkorlikni pullik bosqichga o‘tkazishni rejalashtiryapmiz.',
  },
  {
    id: 'growth', label: 'Growth strategy', theme: 'light', layout: 'growth',
    title: 'Local proof before\ninternational growth.',
    lead: 'Proposed growth path: local proof, wider distribution, then one international test market.',
    shortSeconds: 20, fullSeconds: 40,
    short: 'Global bozorga chiqishni bosqichma-bosqich quramiz. Avval hozirgi beshta markaz bilan sinovdagi foydalanish va pullik xizmatga o‘tishni o‘lchaymiz. Keyin tasdiqlangan natijalar orqali boshqa markazlarga chiqamiz. So‘ng bitta xalqaro bozorda kichik marketing sinovini o‘tkazib, mijoz jalb qilish xarajati va qayta foydalanishni tekshiramiz.',
    full: 'Bizning uzoq muddatli maqsadimiz xalqaro bozor. Taklif qilayotgan yo‘limiz uch bosqichdan iborat. Birinchi bosqichda hozirgi beshta markaz bilan sinovni o‘lchaymiz: faollik, topshiriq bajarilishi, qayta foydalanish va pullik xizmatga o‘tish. Keyin ruxsat bilan olingan haqiqiy tajribalarni boshqa markazlarga chiqishda ishlatamiz. Uchinchi bosqichda bitta xalqaro test bozorini tanlaymiz. Inglizcha mahsulot namoyishi va cheklangan reklama sinovi orqali jalb qilish xarajati, qayta foydalanish va to‘lashga tayyorlikni tekshiramiz. Natija yaxshi bo‘lsa, o‘sishni kengaytiramiz.',
  },
  {
    id: 'team', label: 'The team', theme: 'dark', layout: 'team',
    title: 'A team covering product,\ndevelopment and marketing.',
    lead: 'ProfAI is built and launched. The next job is to turn early interest into repeat use.',
    shortSeconds: 15, fullSeconds: 30,
    short: 'Jamoamizda men, Elyor Nishonboyev, asoschi sifatida ishlayman. Amirbek Mansurov marketing yo‘nalishiga mas’ul. Davlat Erkinov va Alimqulov Firdavs dasturchilarimiz. Biz mahsulotni ishga tushirdik. Endi dastlabki qiziqishni muntazam foydalanish va barqaror tijorat hamkorligiga aylantirish ustida ishlaymiz.',
    full: 'Jamoamizda men, Elyor Nishonboyev, asoschi sifatida ishlayman va bugun loyihani taqdim etyapman. Amirbek Mansurov marketing yo‘nalishiga mas’ul. Davlat Erkinov va Alimqulov Firdavs dasturchilarimiz. Shu jamoa bilan mahsulotni yaratdik va ishga tushirdik. Hozir texnik rivojlanish bilan birga markazlarning fikrini yig‘ish, foydalanishdagi to‘siqlarni tuzatish va mijoz jalb qilishni yo‘lga qo‘yishga e’tibor qaratamiz. Marketing bo‘yicha tajribali hamkorning yordami shu bosqichni kuchaytiradi.',
  },
  {
    id: 'ask', label: 'The ask', theme: 'dark', layout: 'ask',
    title: 'Help ProfAI reach\nits next learning centers.',
    lead: 'A proposed 90-day growth partnership, with a path to international distribution.',
    shortSeconds: 15, fullSeconds: 30,
    short: 'Sizdan reklama va mijoz jalb qilish bo‘yicha amaliy yordam, o‘quv markazlari bilan tanishtirish va xalqaro bozor bo‘yicha mentorlik so‘raymiz. Taklifimiz: 90 kunlik o‘sish rejasini birga tuzish. Keyingi qadam sifatida alohida uchrashuvda yordam ko‘lami va o‘lchanadigan natijalarni kelishishni istaymiz. Rahmat.',
    full: 'Sizdan uch yo‘nalishda amaliy yordam so‘raymiz. Birinchisi, reklama va mijoz jalb qilishni rejalashtirish, jumladan kichik reklama sinovlarini qo‘llab-quvvatlash. Ikkinchisi, yangi o‘quv markazlari va ta’lim hamkorlari bilan tanishtirish. Uchinchisi, xalqaro bozorni tanlash va unga chiqish bo‘yicha mentorlik. Taklifimiz 90 kunlik o‘sish hamkorligi. Keyingi qadam sifatida alohida uchrashuvda yordam ko‘lami, reklama byudjeti va o‘lchanadigan natijalarni birga kelishishni istaymiz. ProfAI’ni profai.uz orqali ko‘rishingiz mumkin. Rahmat.',
  },
  {
    id: 'pricing', label: 'Appendix: pricing', theme: 'light', layout: 'pricing', appendix: true,
    title: 'Current listed plans',
    lead: 'One-month prices configured in the repository. Center agreements are negotiated separately.',
    short: 'Bu narxlar manba kodida ko‘rsatilgan bir oylik tariflar. O‘quvchi uchun olti dollar, markaz o‘quvchisi uchun to‘rt dollar, o‘qituvchi uchun sakkiz dollar. Markazlar bilan yakuniy hamkorlik shartlarini alohida kelishamiz. Bu narxlar haqiqiy tushum yoki tuzilgan shartnomani bildirmaydi.',
    full: 'Bu narxlar manba kodida ko‘rsatilgan bir oylik tariflar. O‘quvchi uchun olti dollar, markaz o‘quvchisi uchun to‘rt dollar, o‘qituvchi uchun sakkiz dollar. Tariflarda foydalanish tangalari bor, qo‘shimcha paketlar ham mavjud. Markazlar bilan yakuniy hamkorlik shartlari alohida kelishiladi. Narxlar tirik saytdagi to‘lov jarayonidan mustaqil ravishda tekshirilmagan va ular haqiqiy tushum yoki tuzilgan shartnomani bildirmaydi.',
  },
  {
    id: 'pilot', label: 'Appendix: pilot evidence', theme: 'light', layout: 'pilot', appendix: true,
    title: 'What the 14-day trial\nshould prove',
    lead: 'A proposed scorecard for learning-center trials, before wider advertising.',
    short: 'Sinovda faqat ro‘yxatdan o‘tganlar sonini emas, real foydalanishni tekshiramiz. O‘qituvchi topshiriq beradimi, o‘quvchi bajaradimi, keyingi haftada qaytib keladimi va markaz pullik xizmatga o‘tishga tayyormi? Shu ko‘rsatkichlar marketingni kengaytirish qaroriga asos bo‘ladi.',
    full: 'Bu sinov uchun taklif qilayotgan o‘lchov jadvalimiz. Avval faollashuvni tekshiramiz: o‘qituvchi sinf ochib vazifa berdimi, o‘quvchi birinchi topshiriqni bajardimi? Keyin topshiriq bajarilishi va keyingi haftada qayta foydalanishni o‘lchaymiz. O‘qituvchidan tekshirish va kuzatishga ketadigan vaqt bo‘yicha sinovdan oldingi va keyingi ma’lumotni so‘raymiz. Oxirida markazning pullik hamkorlikka tayyorligini aniqlaymiz. Hozircha bular erishilgan natijalar emas, sinovda o‘lchash uchun taklif qilayotgan ko‘rsatkichlar.',
  },
];

export const sources = [
  { name: 'Founder-supplied facts', detail: '40 users on launch day 3; 5 learning centers in partnership discussions; a 14-day trial offered; team and contact supplied in this conversation on 7 October 2026.' },
  { name: 'Class assignments', path: 'src/features/learningCenter/AssignmentsView.tsx', detail: 'Group/individual assignment delivery, deadlines and completion tracking.' },
  { name: 'Student results and teacher notes', path: 'src/features/learningCenter/StudentDetailView.tsx; src/features/learningCenter/TeacherNotesPanel.tsx', detail: 'Recorded results, skill breakdown, insights, teacher notes and student notification delivery.' },
  { name: 'Current pricing configuration', path: 'backend/src/utils/billingCatalog.ts', detail: 'One-month LEARNER $6 with 1,000 coins, CENTER_STUDENT $4 with 600 coins, TEACHER $8 with 1,000 coins. Configuration only, not independently verified live prices.' },
  { name: 'YC: clear slide design', url: 'https://www.ycombinator.com/blog/how-to-design-a-better-pitch-deck/' },
  { name: 'YC: pitch narrative and rehearsal', url: 'https://www.ycombinator.com/blog/guide-to-demo-day-pitches/' },
  { name: 'Sequoia: company, problem, solution, market, alternatives, model and team', url: 'https://sequoiacap.com/article/writing-a-business-plan/' },
];
