import { useState } from 'react'
import { Copy, Mail, Plus, ShieldCheck, UserRoundCheck } from 'lucide-react'
import { useAsyncData } from '@/hooks/useAsyncData'
import { learningCenterApi } from './api'
import { Avatar, CenterPageHeading, CenterPanel, CenterSkeleton, EmptyState, ErrorState, inputClass, Modal, primaryButton, secondaryButton } from './components'
import type { CenterRole } from './types'

export default function TeamView({ slug, canManage }: { slug: string; canManage: boolean }) {
  const [open, setOpen] = useState(false)
  const { data, loading, error, refetch } = useAsyncData(() => learningCenterApi.team(slug), [slug])
  return <div className="space-y-6"><CenterPageHeading eyebrow="People & permissions" title="A teaching team with clear ownership" description="Workspace roles protect student data while giving each teacher exactly the cohorts they need." action={canManage ? <button type="button" onClick={() => setOpen(true)} className={primaryButton}><Plus className="h-4 w-4" /> Add team member</button> : undefined} />{loading && !data ? <CenterSkeleton blocks={6} /> : error && !data ? <ErrorState message={error} onRetry={() => void refetch()} /> : data?.team.length ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{data.team.map((member) => <CenterPanel key={member.id} className="p-5"><div className="flex items-start justify-between"><Avatar name={member.user.fullName} url={member.user.avatarUrl} size="lg" /><span className={`rounded-full px-2.5 py-1 text-[9px] font-black uppercase tracking-wider ${member.role === 'OWNER' ? 'bg-violet-50 text-violet-700' : member.role === 'ADMIN' ? 'bg-blue-50 text-blue-700' : 'bg-emerald-50 text-emerald-700'}`}>{member.role}</span></div><h2 className="mt-4 text-lg font-black text-slate-950">{member.user.fullName}</h2><p className="mt-1 flex items-center gap-1.5 text-xs font-semibold text-slate-500"><Mail className="h-3.5 w-3.5" />{member.user.email}</p><div className="mt-4 flex items-center justify-between rounded-xl bg-slate-50 px-3 py-2.5"><span className="text-[10px] font-bold uppercase tracking-wider text-slate-400">Assigned groups</span><strong className="text-sm text-slate-900">{member.groupCount}</strong></div><p className="mt-3 text-[10px] font-semibold text-slate-400">Joined {new Date(member.joinedAt).toLocaleDateString()}</p></CenterPanel>)}</div> : <CenterPanel><EmptyState title="Build your academic team" description="Invite teachers and administrators using their ProfAI email or a secure onboarding link." /></CenterPanel>}<InviteTeamModal open={open} onClose={() => setOpen(false)} slug={slug} onDone={() => { setOpen(false); void refetch() }} /></div>
}

function InviteTeamModal({ open, onClose, slug, onDone }: { open: boolean; onClose: () => void; slug: string; onDone: () => void }) {
  const [email, setEmail] = useState('')
  const [role, setRole] = useState<Exclude<CenterRole, 'OWNER' | 'STUDENT'>>('TEACHER')
  const [title, setTitle] = useState('')
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState('')
  const [invitePath, setInvitePath] = useState('')
  async function submit(event: React.FormEvent) { event.preventDefault(); setBusy(true); setError(''); try { const response = await learningCenterApi.invite(slug, { email: email || undefined, role, title: title || undefined }); if (response.status === 'MEMBER_ADDED') onDone(); else setInvitePath(response.invitation?.joinPath ?? '') } catch (submitError) { setError(submitError instanceof Error ? submitError.message : 'Could not invite team member.') } finally { setBusy(false) } }
  const link = invitePath ? `${window.location.origin}${invitePath}` : ''
  return <Modal open={open} onClose={onClose} title="Add a team member" description="Existing users connect immediately; everyone else receives a secure invitation link.">{invitePath ? <div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-4"><p className="text-sm font-black text-emerald-900">Invitation ready</p><p className="mt-2 break-all text-xs font-semibold text-emerald-700">{link}</p><button type="button" onClick={() => void navigator.clipboard.writeText(link)} className={`${secondaryButton} mt-4`}><Copy className="h-4 w-4" /> Copy link</button></div> : <form onSubmit={submit} className="space-y-4"><label className="block"><span className="mb-1.5 block text-xs font-black text-slate-700">Work email</span><input type="email" value={email} onChange={(event) => setEmail(event.target.value)} className={inputClass} placeholder="teacher@center.uz" /></label><div className="grid gap-3 sm:grid-cols-2"><label><span className="mb-1.5 block text-xs font-black text-slate-700">Workspace role</span><select value={role} onChange={(event) => setRole(event.target.value as typeof role)} className={inputClass}><option value="TEACHER">Teacher</option><option value="ADMIN">Administrator</option></select></label><label><span className="mb-1.5 block text-xs font-black text-slate-700">Professional title</span><input value={title} onChange={(event) => setTitle(event.target.value)} className={inputClass} placeholder="Senior SAT Teacher" /></label></div><div className="rounded-2xl border border-blue-100 bg-blue-50/70 p-4"><div className="flex gap-3"><ShieldCheck className="h-5 w-5 shrink-0 text-blue-600" /><p className="text-xs font-semibold leading-5 text-blue-800">Teachers see only students in their assigned groups. Administrators can manage the complete workspace.</p></div></div>{error ? <p className="rounded-xl bg-red-50 px-3 py-2 text-xs font-bold text-red-700">{error}</p> : null}<div className="flex justify-end gap-2"><button type="button" onClick={onClose} className={secondaryButton}>Cancel</button><button disabled={busy} className={primaryButton}><UserRoundCheck className="h-4 w-4" />{busy ? 'Inviting...' : 'Add member'}</button></div></form>}</Modal>
}
