import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { ArrowRight, BarChart3, BrainCircuit, Building2, CheckCircle2, GraduationCap, Plus, ShieldCheck, Sparkles, Users } from 'lucide-react'
import { motion } from 'framer-motion'
import { BrandMark } from '@/components/brand/BrandLogo'
import { useAsyncData } from '@/hooks/useAsyncData'
import { learningCenterApi } from '@/features/learningCenter/api'
import { CenterPanel, CenterSkeleton, ErrorState, inputClass, Modal, primaryButton, secondaryButton } from '@/features/learningCenter/components'
import { useAuthStore } from '@/store/authStore'

export default function LearningCenterPortal() {
  const navigate = useNavigate()
  const user = useAuthStore((state) => state.user)
  const [open, setOpen] = useState(false)
  const { data, loading, error, refetch } = useAsyncData(
    () => user ? learningCenterApi.workspaces() : Promise.resolve({ workspaces: [] }),
    [user?.id],
  )
  useEffect(() => {
    if (!open || user) return
    setOpen(false)
    navigate('/register')
  }, [navigate, open, user])
  return (
    <div className="min-h-screen overflow-x-hidden bg-[radial-gradient(circle_at_8%_0%,rgba(59,130,246,.15),transparent_28%),radial-gradient(circle_at_96%_18%,rgba(239,68,68,.1),transparent_25%),#f8fafc] px-4 py-6 sm:px-6 lg:px-10">
      <header className="mx-auto flex max-w-7xl items-center justify-between gap-3"><button type="button" onClick={() => navigate('/dashboard')} className="flex min-w-0 items-center gap-2 sm:gap-3"><BrandMark size={44} /><div className="min-w-0 text-left"><p className="truncate text-xl font-black tracking-[-.05em] text-slate-950">Prof<span className="text-red-600">AI</span></p><p className="truncate text-[8px] font-black uppercase tracking-[.18em] text-slate-400">Learning Centers</p></div></button><button type="button" onClick={() => navigate('/dashboard')} aria-label="Open student platform" className={`${secondaryButton} shrink-0 px-3 sm:px-4`}><span className="hidden sm:inline">Student platform</span><ArrowRight className="h-4 w-4" /></button></header>
      <main className="mx-auto max-w-7xl pb-16 pt-10 sm:pt-16">
        <div className="grid items-center gap-10 lg:grid-cols-[1.05fr_.95fr]">
          <div><span className="inline-flex items-center gap-2 rounded-full border border-blue-200 bg-white/80 px-3 py-1.5 text-[10px] font-black uppercase tracking-[.16em] text-blue-700 shadow-sm"><Sparkles className="h-3.5 w-3.5" /> Academic operating system</span><h1 className="mt-5 max-w-3xl text-4xl font-black leading-[.96] tracking-[-.06em] text-slate-950 sm:text-6xl">Teach. Track.<br /><span className="bg-gradient-to-r from-blue-600 via-indigo-600 to-red-500 bg-clip-text text-transparent">Analyze. Improve.</span></h1><p className="mt-6 max-w-xl text-base font-medium leading-7 text-slate-600">One intelligent workspace for IELTS and SAT centers to manage groups, monitor every learner, deliver assignments and turn data into better teaching decisions.</p><div className="mt-7 flex flex-wrap gap-3"><button type="button" onClick={() => setOpen(true)} className={`${primaryButton} min-h-12 px-5`}><Building2 className="h-5 w-5" /> Create center workspace</button>{data?.workspaces[0] ? <button type="button" onClick={() => navigate(`/learning-center/${data.workspaces[0].slug}`)} className={`${secondaryButton} min-h-12 px-5`}>Open dashboard <ArrowRight className="h-4 w-4" /></button> : null}</div><div className="mt-8 grid max-w-xl grid-cols-3 gap-3"><Trust icon={ShieldCheck} label="Scoped access" /><Trust icon={BrainCircuit} label="AI insights" /><Trust icon={BarChart3} label="Live progress" /></div></div>
              <motion.div initial={{ opacity: 0, y: 24 }} animate={{ opacity: 1, y: 0 }} className="relative"><div className="absolute -inset-5 rounded-[3rem] bg-gradient-to-br from-blue-300/25 to-red-200/20 blur-2xl" /><CenterPanel className="relative p-4 sm:p-6"><div className="rounded-[1.6rem] bg-[linear-gradient(135deg,#0f172a,#172554_64%,#1d4ed8)] p-5 text-white"><div className="flex items-center justify-between"><div><p className="text-[9px] font-black uppercase tracking-[.18em] text-blue-200">Center overview</p><h2 className="mt-1 text-xl font-black">Academic command center</h2></div><span className="grid h-10 w-10 place-items-center rounded-xl border border-white/10 bg-white/10"><GraduationCap className="h-5 w-5" /></span></div><div className="mt-5 grid grid-cols-2 gap-3"><PreviewMetric label="Student data" value="Live" /><PreviewMetric label="Analysis" value="AI" /><PreviewMetric label="Exam track" value="SAT" /><PreviewMetric label="Exam track" value="IELTS" /></div></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><PreviewCard icon={Users} title="Cohort intelligence" text="Spot momentum and intervention needs early." /><PreviewCard icon={BrainCircuit} title="ProfAI analysis" text="Translate results into a focused 7-day plan." /></div></CenterPanel></motion.div>
        </div>

        <section className="mt-16"><div className="flex items-end justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.2em] text-blue-600">Your organization</p><h2 className="mt-1 text-2xl font-black tracking-[-.04em] text-slate-950">Learning center workspaces</h2></div>{data?.workspaces.length ? <button type="button" onClick={() => setOpen(true)} className={secondaryButton}><Plus className="h-4 w-4" /> New workspace</button> : null}</div><div className="mt-5">{loading && !data ? <CenterSkeleton blocks={3} /> : error && !data ? <ErrorState message={error} onRetry={() => void refetch()} /> : data?.workspaces.length ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{data.workspaces.map((workspace) => <button key={workspace.id} type="button" onClick={() => navigate(`/learning-center/${workspace.slug}`)} className="group rounded-[1.5rem] border border-white bg-white/90 p-5 text-left shadow-[0_18px_50px_rgba(15,23,42,.07)] transition hover:-translate-y-1 hover:shadow-[0_24px_60px_rgba(30,64,175,.14)]"><div className="flex items-start justify-between"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-gradient-to-br from-blue-600 to-indigo-600 text-lg font-black text-white shadow-lg shadow-blue-500/20">{workspace.name[0]}</span><span className="rounded-full bg-blue-50 px-2.5 py-1 text-[9px] font-black uppercase tracking-wider text-blue-700">{workspace.role}</span></div><h3 className="mt-4 text-lg font-black text-slate-950">{workspace.name}</h3><p className="mt-1 text-xs font-semibold text-slate-400">{workspace.city || 'Location not set'}</p><div className="mt-4 flex items-center gap-4 text-[11px] font-bold text-slate-500"><span>{workspace.memberCount} members</span><span>{workspace.groupCount} groups</span><ArrowRight className="ml-auto h-4 w-4 transition group-hover:translate-x-1 group-hover:text-blue-600" /></div></button>)}</div> : <CenterPanel className="p-6 text-center"><CheckCircle2 className="mx-auto h-7 w-7 text-blue-600" /><h3 className="mt-3 text-lg font-black text-slate-950">Your first command center is one step away</h3><p className="mx-auto mt-2 max-w-lg text-sm text-slate-500">Create a workspace, invite your team, add groups and connect existing ProfAI students.</p></CenterPanel>}</div></section>
      </main>
      <CreateWorkspaceModal open={open} onClose={() => setOpen(false)} onCreated={(slug) => navigate(`/learning-center/${slug}`)} />
    </div>
  )
}

function Trust({ icon: Icon, label }: { icon: typeof ShieldCheck; label: string }) { return <span className="flex items-center gap-2 text-[11px] font-bold text-slate-600"><Icon className="h-4 w-4 text-blue-600" />{label}</span> }
function PreviewMetric({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-white/10 bg-white/[.08] p-3"><p className="text-[8px] font-black uppercase tracking-wider text-blue-200">{label}</p><p className="mt-1 text-xl font-black">{value}</p></div> }
function PreviewCard({ icon: Icon, title, text }: { icon: typeof Users; title: string; text: string }) { return <div className="rounded-2xl border border-slate-100 bg-slate-50/70 p-4"><Icon className="h-5 w-5 text-blue-600" /><p className="mt-3 text-sm font-black text-slate-900">{title}</p><p className="mt-1 text-xs leading-5 text-slate-500">{text}</p></div> }

function CreateWorkspaceModal({ open, onClose, onCreated }: { open: boolean; onClose: () => void; onCreated: (slug: string) => void }) {
  const [name, setName] = useState(''); const [city, setCity] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState('')
  async function submit(event: React.FormEvent) { event.preventDefault(); setBusy(true); setError(''); try { const response = await learningCenterApi.createWorkspace({ name, city: city || undefined, timezone: Intl.DateTimeFormat().resolvedOptions().timeZone || 'Asia/Tashkent' }); onCreated(response.workspace.slug) } catch (submitError) { setError(submitError instanceof Error ? submitError.message : 'Could not create workspace.') } finally { setBusy(false) } }
  return <Modal open={open} onClose={onClose} title="Create your center workspace" description="Start with the organization basics. You can add teachers, groups and students next."><form onSubmit={submit} className="space-y-4"><label className="block"><span className="mb-1.5 block text-xs font-black text-slate-700">Learning center name</span><input required minLength={3} value={name} onChange={(event) => setName(event.target.value)} className={inputClass} placeholder="Oxford Learning Center" /></label><label className="block"><span className="mb-1.5 block text-xs font-black text-slate-700">City</span><input value={city} onChange={(event) => setCity(event.target.value)} className={inputClass} placeholder="Tashkent" /></label>{error ? <p className="rounded-xl bg-red-50 px-3 py-2 text-xs font-bold text-red-700">{error}</p> : null}<div className="flex justify-end gap-2"><button type="button" onClick={onClose} className={secondaryButton}>Cancel</button><button disabled={busy} className={primaryButton}><Building2 className="h-4 w-4" />{busy ? 'Creating...' : 'Create workspace'}</button></div></form></Modal>
}
