export type SourceTaskVisual = {
  kind: 'Line graph' | 'Bar chart' | 'Table' | 'Charts' | 'Maps' | 'Process diagram'
  title: string
  lead: string
  context: string
  extension: 'png' | 'jpg' | 'webp'
  sourceUrl: string
}

// The image files are unmodified copies of the task visuals shown in the supplied screenshots.
export const SOURCE_TASK_VISUALS: Record<number, SourceTaskVisual> = {
  5: {
    kind: 'Charts', title: 'Fish imported to the US',
    lead: 'The table and pie charts give information about the total value and sources of fish imported to the US between 1988 and 2000.',
    context: 'Total import value in billions of US dollars: 1988 6.57, 1992 8.52, 2000 10.72. Source shares (China, Canada, Others): 1988 13%, 60%, 27%; 1992 20%, 34%, 46%; 2000 30%, 28%, 42%.',
    extension: 'png', sourceUrl: 'https://ieltsliz.com/ielts-table-three-pie-charts-model/',
  },
  6: {
    kind: 'Process diagram', title: 'Rainwater for drinking',
    lead: 'The diagram shows how rainwater is collected for the use of drinking water in an Australian town.',
    context: 'Rainwater falls onto the roofs of houses, runs through gutters and drains into a shared pipe, passes through a water filter into a storage tank, then flows to a treatment tank. Chemicals are added before drinking water is piped back to the houses and their taps.',
    extension: 'jpg', sourceUrl: 'https://ieltsliz.com/ielts-diagram/',
  },
  7: {
    kind: 'Maps', title: 'Changes in Nelson',
    lead: 'The maps below show changes in the city of Nelson in recent times.',
    context: 'Nelson in 2000 versus today. The university and port remain. A hall of residence was added to the northwest of the university and a shopping centre replaced trees to its east. The train station moved from the west to the area north of the city centre. A tramline now links the university to the centre. The old market became a shop, a covered market was added east of the centre, a bike rental scheme occupies the centre, the road became pedestrian only, and a restaurant plus bars and clubs were added by the port.',
    extension: 'webp', sourceUrl: 'https://9ielts.com/changes-in-the-city-of-nelson-in-recent-times',
  },
  8: {
    kind: 'Line graph', title: 'UK radio and television audiences',
    lead: 'The line graph below shows radio and television audiences throughout the day in 1992.',
    context: 'Radio and television audiences in the UK from October to December 1992, as percentages of people over four across the day. Radio peaks at about 26% around 8 a.m., then declines. Television stays below 10% through the morning, rises sharply in the late afternoon and peaks near 45% around 8 to 9 p.m. Both are low overnight.',
    extension: 'png', sourceUrl: 'https://ieltsliz.com/ielts-line-graph-sample-answer/',
  },
  9: {
    kind: 'Table', title: 'Spending on four items in the UK',
    lead: 'The table shows the proportion of income adults and children spent on four common items in the UK in 1998.',
    context: 'Percent of income spent on food, electronic equipment, music, videos respectively in the UK in 1998. Adults: 25, 5, 5, 1. Men: 14, 10, 5, 2. Women: 39, 1, 5, 0.5. Children: 10, 23, 39, 12. Boys: 9, 18, 38, 18. Girls: 11, 5, 40, 17.',
    extension: 'png', sourceUrl: 'https://ieltsliz.com/ielts-table-spending-on-items/',
  },
  10: {
    kind: 'Process diagram', title: 'Ladybird life cycle and anatomy',
    lead: 'The diagrams below show the life cycle of a lady bird and its anatomy.',
    context: 'Life cycle: eggs laid on a leaf for 2–5 days; larval stage lasts 21 days; pupa on a leaf lasts 7 days; an adult ladybird emerges and reproduces. Anatomy labels include head, antenna, eye, pronotum, red elytra with black spots, leg, abdomen and wing.',
    extension: 'png', sourceUrl: 'https://ieltsliz.com/ielts-writing-task-1-life-cycle-diagram/',
  },
  11: {
    kind: 'Bar chart', title: 'Wind energy in four countries',
    lead: 'The bar chart shows the amount of energy generated by wind in four countries from 1985 to 2000.',
    context: 'Energy generated in megawatts for 1985, 1990, 1995 and 2000. India: about 200, 400, 800, 1200. Denmark: about 250, 450, 1200, 1650. Germany: about 400, 650, 820, 900. United States: about 1200, 1650, 1600, 1500. The US leads until Denmark overtakes it in 2000.',
    extension: 'png', sourceUrl: 'https://ieltsliz.com/ielts-bar-chart-model-answer-2023/',
  },
  12: {
    kind: 'Maps', title: 'Meadowside village and Fonton',
    lead: 'The maps below show the changes that have taken place in Meadowside village and Fonton, a neighbouring town, since 1962.',
    context: 'In 1962 Meadowside was a small village separated from Fonton, linked by roads while a railway ran through Fonton. By 1985 Meadowside had grown and gained a housing estate, leisure complex and superstore, and a new road connected the settlements. Today Meadowside is a suburb and the two built-up areas have joined. A hotel, railway station and business park were added, with the railway extended towards Meadowside.',
    extension: 'jpg', sourceUrl: 'https://ieltsunlocked.wordpress.com/2018/11/22/ielts-task-one-basic-to-band-9-maps-fonton-and-meadowside/',
  },
  13: {
    kind: 'Charts', title: 'Arrests by gender and reason',
    lead: 'The charts below show the males and females arrested over 5 years and the reasons for the most recent arrests.',
    context: 'Over the five years ending 1994, 32% of males and 9% of females were arrested. The most recent arrest reasons in percent (males, females approximately): drink driving 26, 14; public drinking 31, 37; breach of order 18, 12; assault 17, 19; theft 16, 13; other reason 19, 18; no answer 4, 7. Public drinking was the leading reason for both genders.',
    extension: 'jpg', sourceUrl: 'https://ieltsliz.com/ielts-charts-writing-task-1/',
  },
  14: {
    kind: 'Process diagram', title: 'Australian water supply systems',
    lead: 'The diagrams below show the water supply system in Australia at present and in future.',
    context: 'Present: pure water from a dam or storage goes to a city containing households, factories and shops. Storm water runs to the river; waste water goes to a water treatment plant and then the river. Future: the dam still supplies the city, while both storm water and waste water go to the water treatment plant and are recycled to the city; neither is discharged to the river.',
    extension: 'png', sourceUrl: 'https://ieltsliz.com/ielts-water-supply-diagram-2015/',
  },
  15: {
    kind: 'Process diagram', title: 'Life cycle of a frog',
    lead: 'The diagram below shows the life cycle of a frog.',
    context: 'Eight stages: adult frogs mate; females lay eggs (frogspawn) in water; tadpoles emerge after 7–10 days and eat algae; legs develop at around 6 and 9 weeks; a froglet begins pulmonary breathing at about 12 weeks; it becomes a young frog and an adult frog after about four years, restarting the cycle.',
    extension: 'png', sourceUrl: 'https://ieltsliz.com/ielts-diagram-introduction-overview-paragraphs/',
  },
  16: {
    kind: 'Bar chart', title: 'Computer ownership by education level',
    lead: 'The bar chart shows computer ownership by education level in 2002 and 2010.',
    context: 'Computer ownership, percent in 2002 and 2010 respectively: no high school diploma about 15 and 42; high school graduate 38 and 66; college incomplete 55 and 85; bachelor’s degree 70 and 90; postgraduate qualification 77 and 95. Ownership rises with education level and rises in every group between the two years.',
    extension: 'png', sourceUrl: 'https://ieltsliz.com/ielts-writing-task-1-introduction/',
  },
  17: {
    kind: 'Bar chart', title: 'Boys and girls playing sport',
    lead: 'The graph shows the number of boys and girls playing sport in an English town in 2012.',
    context: 'Number of boys and girls respectively playing each sport in an English town in 2012: tennis 50 and 37; badminton 30 and 40; cycling 36 and 20; swimming 41 and 50; football 60 and 21; hockey 15 and 9. Football is most popular among boys, swimming among girls, and hockey is least popular among both.',
    extension: 'jpg', sourceUrl: 'https://ieltsliz.com/bar-chart-sample-answer/',
  },
}
